name: Error1
# Contrôler quand le workflow va s’exécuter
on:
  # Déclenche le workflow quand il y a un push ou un pull request sur la branche “main”
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
  
jobs:
  # Ce workflow contient un seul job appelé “build”
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, ${{ inputs.surname }}!
